### ISSUE TITLE
Inactive Role doesn't change to Active when user chats

### ISSUE THREAD

**Issue by yada-yoda** [bhigginsuk/discord-activity-monitor#25]
It seems we've had multiple users not have their Inactive role changed to Active when they start chatting again in the room -- We've checked the settings over and over and previously it did work, but up until recently in the last month. Did something change? Thanks!

**Comment by benji7425** [comment]
Hey, sorry for the delay in replying. Nothing has changed recently that I know of, unless there's some change to Discord's API. It's possible this is a permissions issue. Make sure the bot has read permissions for all the channels that you want it to be able to detect users in. You also need to ensure it's at the top of the roles hierarchy, as Discord only allows it to assign/remove roles below it in the hierarchy.

If you have a deployed either manually or using Docker then you should be able to look at the logs to see whether there are any errors. If I remember correctly there should be a 'logs' directory you can look in under the main folder. Let me know if you need help finding it.

**Comment by heyfrank** [comment]
Thanks for the reply @benji7425  -- I do not have it hosted -- i'm using the kind hosting you may have provided. I have checked the permissions and they're all 100% granted and the bots role sits right below our admin role (for protection). So I do not think that is the issue.

I also was having an issue even trying to view the current config or settings recently -- again it worked fine before as well.

A few last questions -- How long does it take for the "active" role to take over on the "inactive" role or how many message? If I change the role manually from inactive to active due to the bot missing the persons last messages for whatever reason, will this do any harm?

**Comment by benji7425** [comment]
I have not provided a public host myself for many months now, so you most likely invited the bot from https://bots.ol48.uk/, who is a community member. This means I can't directly troubleshoot for you, but you can try contacting him to ask him to look at the logs.

An alternative would be for you to set up your own host so you can access all the log files yourself and do your own troubleshooting. I have a guide here: https://benji7425.io/discord-deployment

As for your other questions; a user should become 'active' after a single message or voice join, there is no kind of threshold they need to reach.

You can also manually update the 'active' and 'inactive' roles without doing any harm. The bot should detect this and update it's database.
