### ISSUE TITLE
Ability to send custom command on inactive determination

### ISSUE THREAD

**Issue by dVIAN13** [bhigginsuk/discord-activity-monitor#5]
Hello, thank you for this amazing and useful bot!

Is it possible to have ActivityMonitor send a 'custom' command to another bot when a user is determined to be 'inactive'? 

We are wanting to reset a user's XP from another bot that has the command to do so..

**Comment by benji7425** [comment]
In order to do this you would need to fork this project and code the message/command yourself, which you are more than welcome to do. The functionality doesn't exist currently.

I could perhaps consider some kind of notification system when users are inactive, for instance "User benji7425 has gone inactive", but sending a custom command along with this is rather niche functionality, so not something I think I can prioritise.
